name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: docker login
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - name: docker build proxy
          run: |
            docker build ./proxy -t michael816/proxy:latest
        - name: docker build sanbar-app
          run: |
            docker build ./sanbar-app -t michael816/sanbar-app:latest
        - name: docker build sanbar-api
          run: |
            docker build ./Sanbar.Api -t michael816/sanbar-api:latest
        - name: docker push
          run: |
            docker push michael816/proxy:latest
            docker push michael816/sanbar-app:latest
            docker push michael816/sanbar-api:latest
