name: Build

on:
  push:
    branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: docker build sanbar-app
          run: |
            docker build -f frontend/linux-arm64.Dockerfile -t michael816/sanbar-app:linux-arm64 frontend
        - name: docker build sanbar-api
          run: |
            docker build -f backend/linux-arm64.Dockerfile -t michael816/sanbar-api:linux-arm64 backend
        - name: docker login
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        - name: docker push
          run: |
            docker push michael816/sanbar-app:linux-arm64
            docker push michael816/sanbar-api:linux-arm64
        - name: setup ssh
          run: |
            mkdir ~/.ssh
            echo "$SSH_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            cat >>~/.ssh/config <<END
            Host $SSH_HOST
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/id_rsa
              StrictHostKeyChecking no
            END
          env:
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_KEY: ${{ secrets.SSH_KEY }}
        - name: docker-compose pull
          run: |
            docker-compose -f docker-compose.prod.yaml pull
          env:
            DOCKER_HOST: ssh://${{ secrets.SSH_HOST }}
        - name: docker-compose up
          run: |
            docker-compose -f docker-compose.prod.yaml up -d --remove-orphans
          env:
            DOCKER_HOST: ssh://${{ secrets.SSH_HOST }}
